### ISSUE TITLE
DWI mask includes non-brain

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#123]
Hi @mattcieslak,

Going through some of the outputs from `0.8.0` and finding that the ```xxx_spce-T1w_desc-brain_mask.nii.gz` file often includes non-brain (eyes, in particular). See image below. Any thoughts on improving the masking or should I just go in and manually edit out the eyes and stuff that is obviously well outside the brain?

![sub-allo104_ses-bline_acq-b_space-T1w_dwiref](https://user-images.githubusercontent.com/18663624/81843476-80b46280-9502-11ea-890d-86d1202746e5.png)

Red is the DWI mask. Pinkish color is the T1 mask overlaid. Overall the T1 mask is better but in this case doesn't cover as far down the brain stem and may miss some gray matter in the cerebellum that would help to define GM/WM boundary.

**Comment by mattcieslak** [comment]
Hi @araikes, DWI masking has been a tricky problem. The final mask that gets written out is a combination of the T1w mask and the DWI mask qsiprep calculates. In your case it looks like the DWI mask included some of the eyes. Since the preprocessing workflow doesn't do any model fitting, you might have better luck doing a preliminary model fit inside the oversized _mask.nii.gz and using GFA or something to better mask white matter voxels.

**Comment by araikes** [comment]
👍 I'll see what I can come up with.

Thanks

**Comment by IRuotsa** [comment]
Hi @mattcieslak and @araikes ! Did you come up with any solution to this problem? I have similar issues and some of the participants have parts of skull included in the `_space-T1w_desc-brain_mask.nii.gz` -file. Would be great if you have any tips how to make the mask better.
<img width="527" alt="desc-resampled_b0ref_svg" src="https://user-images.githubusercontent.com/47354027/112592093-105abb00-8e0e-11eb-909a-b24058d95389.png">

**Comment by mattcieslak** [comment]
synthstrip should solve this in recent versions, please reopen if not
