### ISSUE TITLE
sform problem on qsiprep out

### ISSUE THREAD

**Issue by weiwei-wch** [PennLINC/qsiprep#125]
Hi @mattcieslak 
    recently I finished qisprep preprocessing and feed the out put 'xxxx_space-T1w_desc-preproc_dwi.nii.gz' file into dipy the facing an error code 

File "/usr/local/lib/python3.6/dist-packages/dipy/io/utils.py", line 278, in get_reference_info
    raise ValueError('Invalid affine, contains only zeros.'
ValueError: ('Invalid affine, contains only zeros.Cannot determine voxel order from transformation', 'occurred at index 0')

    which seems to be caused by something wrong in the sform of header of 'xxxx_space-T1w_desc-preproc_dwi.nii.gz', which is a 4X4 array  contains only 0 except last one is 1. I wonder if it is possible to copy the qform to sform in the output file which could solve this problem.

**Comment by mattcieslak** [comment]
You can safely use the qform from these images. They're created in ANTs, which will only use the qform and writes the sform as zeros. Here is some code that does this correctly: https://github.com/nipreps/niworkflows/blob/ac705ebb48ed721265b1eac385b2402a90626316/niworkflows/interfaces/images.py#L603

Could you open an issue for running this on the outputs? It might be a good idea to open an issue in Dipy too, since these images have valid headers.

**Comment by weiwei-wch** [comment]
I am not sure what you mean about open a new issue about running the 'images.py' , but here is how I do the copy followed the guide you offered：

import nibabel as nb
img = nb.load('dwi/output/of/qsiprep')
qform = img.header.get_qform()
qform_code = int(img.header._structarr['qform_code'])
img.header.set_sform(qform,qform_code)
img.to_filename('filename/of/output')

then the output can be used by dipy
