### ISSUE TITLE
Option to reorient output to remove flips from image header

### ISSUE THREAD

**Issue by jyeatman** [PennLINC/qsiprep#186]
I have been try to use qsi-prep to preprocess data that will eventually be analyzed in a variety of other software packages and I am consistently running into problems that I think are due to:
- The flips that are written into the image header. In the case of my Phillips data the output nifti has a flip over the x and y axis
- The empty sto_xyz transform
qsi-prep's interoperability with other widely used software packages would increase if there were an option to reorient the final images such that there are not flips written into the header.

**Comment by mattcieslak** [comment]
Hi @jyeatman which software specifically is having trouble with the orientation of the output data? The voxel to RAS transform is in the qform in the output images and the sform is not included. This is due to how ITK/ANTs writes to the nifti format. I think copying from the qform to sform is a good idea and should be implemented since it's a quick fix and lots of other software uses this field. 

Keeping the outputs in LPS+, as it's currently written, helps a lot with converting between Dipy/DSI Studio/MRtrix. What about a compromise where we add a reconstruction workflow that writes the entire output in LAS+? That workflow could then be the input to other reconstruction workflows that are expecting fsl standard orientation

**Comment by cookpa** [comment]
ITK recently changed to use the sform instead of the qform for NIFTI transforms. I am working to include this in the next ANTs release. The underlying conventions are not changing, but using the sform will make the headers easier to read and manipulate as needed. It should also improve precision.

**Comment by jyeatman** [comment]
@mattcieslak I think that could work. Isn't RAS the default for freesurfer? I was trying to run the qsi-prep output through [AFQ](https://github.com/yeatmanlab/AFQ) and this is the first time I've run into issues with image orientation. This makes me realize that the libraries AFQ depends on (mainly [vistasoft](https://github.com/vistalab/vistasoft)) are probably not handling all the various image orientations correctly. But I'm also confused as to the source of this because I have never run into this problem before. We are no longer supporting the matlab version of AFQ (as you know all development is on [pyAFQ](https://github.com/yeatmanlab/pyAFQ)), but I think there will continue to be many matlab AFQ users for some time. I think allowing the user a couple choices for the output would be incredibly helpful for the interoperability with different packages that have different assumptions

**Comment by jyeatman** [comment]
@mattcieslak I think the option that you mentioned above will work ass well

**Comment by jyeatman** [comment]
@mattcieslak I think the option you noted above would work as well.
