### ISSUE TITLE
Running subjects with multiple sessions without averaging the T1

### ISSUE THREAD

**Issue by JoelleJee** [PennLINC/qsiprep#245]
Hello Matt,

I have a few subjects with multiple sessions that I want to run through qsiprep. In the documentation it says that the structural images will be averaged across sessions. Is there a way to process the sessions individually to see assess the longitudinal changes in the subject?

Thanks.

**Comment by mattcieslak** [comment]
Hi @JoelleJee, there isn't an elegant method for dealing with this just yet. You have a couple options, though. you could

 * Use BIDS subject identifiers that differ by session, like instead of sub-X_ses1, sub-X_ses2 do sub-X1, sub-X2
 * Run one session at a time by creating a temporary directory with just a single session in it

But the best option probably is to do `--dwi-only` to completely ignore the anatomical data. Then you can process the anats outside of qsiprep however you'd like and bring them back in for the reconstruction workflows.

**Comment by JoelleJee** [comment]
Will try one of those options. Thanks for your help!
