### ISSUE TITLE
Using Lesion Map with ACT/5ttgen/5ttedit

### ISSUE THREAD

**Issue by m-petersen** [PennLINC/qsiprep#276]
Dear Matt,

I'd like to to apply qsiprep using mrtrix_multishell_msmt to a pathological sample containing substantial white matter hyperintensities. For previous analyses we used a custom nipype pipeline feeding a lesion mask into 5ttedit to address potential tracking problems emerging from erroneous segmentations during ACT. Is it possible to do that with qsiprep? Searching the documentation (custom pipelines etc.) wasn't successful.

Thanks!

Sincerely,
Marvin

**Comment by mattcieslak** [comment]
Hi Marvin,

What does your custom pipeline take as input? Preprocessed DWI data or msmt outputs? If it's expecting preprocessed DWI data you can use [this interface](https://github.com/PennLINC/qsiprep/blob/c47af4cdf4c8e686961ba23351c7774746faa4ae/qsiprep/interfaces/bids.py#L80) instead of a data grabber to get qsiprep outputs in to your workflow. 

I'd recommend sticking with your already-working workflow if possible, using qsiprep preprocessed data as inputs. Until qsiprep has more features for reading data for reconstruction mode I'm not sure how we'd fit in the lesion data. In case you're interested, [here](https://github.com/PennLINC/qsiprep/blob/master/qsiprep/workflows/recon/mrtrix.py#L31) is our msmt workflow implementation.

**Comment by m-petersen** [comment]
Thanks for your help, Matt. Inputs are raw DWI and structural data. Like qsiprep it provides the whole service from raw to connectome. However, its from 2017 missing a lot of the advancements qsiprep covers. I'll see what I can do with my old workflow.
