### ISSUE TITLE
output folder-qsirecon only have logs folder

### ISSUE THREAD

**Issue by JING-797** [PennLINC/qsiprep#288]
Hi Matt,

When i used the qsiprep,i was confused with some questions. I sincerely hope you can solve my problems if it is convenient for you.

q1,With the default options, the pipeline only implemented preprocessing, and the reconstruction results were not automatically generated, Do I need to set any specfic options according to the dMRI data (e.g. --recon-spec argument)?

q2, The qsiprep have completed preprocessing pipeline, and generated qsiprep folders, but there wa no any reconstruction results . In the output dir, there was only log folder in the qsirecon folder. It reported erros in the process.

210821-17:50:56,732 nipype.workflow INFO:
	 [Node] Finished "qsiprep_wf.single_subject_001_wf.dwi_finalize_acq_diff_wf.ds_interactive_report".
210821-17:50:56,732 nipype.workflow INFO:
	 [Job 108] Completed (qsiprep_wf.single_subject_001_wf.dwi_finalize_acq_diff_wf.ds_interactive_report).
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

 q3,I wanna continue analysis, if i chose the" --recon-spec"  option, what  the output dir should be input, like this " --output_dir /where/my/reconstructed/data/goes" ,Does it refer to the "sub-XX"folder generated in the proprecessing pipeline output?

$ qsiprep-docker \
    --bids_dir /path/to/bids \
    --recon_input /output/from/qsiprep \
    --recon_spec gqi_scalar_export.json \
    --output_dir /where/my/reconstructed/data/goes \
    --analysis_level participant \
    --fs-license-file /path/to/license.txt

**Comment by lalade123** [comment]
@mattcieslak

**Comment by smeisler** [comment]
1) Yes, for qsirecon to run , `--recon-spec` must be specified
2) That error doesn't actually seem to be a problem, since it comes after the last step of preprocessing (that is, creation of the interactive reports)
3) the output dir does not need to change for running reconstruction. That is, you can use the same one as qsiprep (e.g. /bids/derivatives/). If you want to use your previously computed results, you can specify `--recon-only` and `--recon-input`, which should point to your qsiprep output folder (e.g. /bids/derivatives/qsiprep)
