### ISSUE TITLE
Does `--dwi-only` still require a T1w image?

### ISSUE THREAD

**Issue by arokem** [PennLINC/qsiprep#340]
Hello! I am trying to process a dataset where no T1w images are available. I thought that maybe running qsiprep with the `--dwi-only` flag would work, but I am still getting a validation error: 

```
1: [ERR] Dataset does not contain any T1w scans. (code: 53 - NO_T1W)
```

Here is my call to qsiprep: 

```
qsiprep ivim ./outputs participant --output-resolution 1.8 -w ./work --nthreads 8 --omp-nthreads 8 --fs-license-file fs_license.txt --dwi-only --dwi-denoise-window 5 --unringing-method mrdegibbs --dwi-no-biascorr
```
And the contents of the `ivim` directory are: 

```
ivim/dataset_description.json
ivim/sub-FS1/dwi/sub-FS1_dwi.bval
ivim/sub-FS1/dwi/sub-FS1_dwi.bvec
ivim/sub-FS1/dwi/sub-FS1_dwi.nii
```
The call is being issued inside of the `pennbbl/qsiprep:0.14.3` docker container on AWS Batch, in case that's important (and is also what makes debugging this a bit tricky...). 

Is this supposed to work?

**Comment by mattcieslak** [comment]
Hi Ariel,

You should be able to add `--skip-bids-validation` and get around this issue. This is definitely a bug though.

One other thing to be aware of is that the reconstruction workflows don't currently work with --dwi-only because they expect the warp to get the atlases lined up with the DWI. This is high on our list to fix too

**Comment by arokem** [comment]
Thanks! Can confirm that skipping bids validation does move me to the next step here. Feel free to close this issue if the bug is already recorded elsewhere, or keep it open if you want to use it to keep track of that.
