### ISSUE TITLE
--do-reconall doesn't seem to work in v 0.15.x

### ISSUE THREAD

**Issue by giulia-berto** [PennLINC/qsiprep#384]
The option `--do-reconall` doesn't seem to work in docker pennbbl/qsiprep:0.15.1 and pennbbl/qsiprep:0.15.3. I get the following error:
```
Falling back to 'CITATION'
Cannot run qsiprep. Missing dependencies:
	mri_label2vol (Interface: Label2Vol)
	mri_label2vol (Interface: Label2Vol)
	mri_convert (Interface: MRIConvert)
	mri_convert (Interface: MRIConvert)
	mris_convert (Interface: MRIsConvert)
	mris_expand (Interface: MakeMidthickness)
	recon-all (Interface: ReconAll)
	recon-all (Interface: ReconAll)
	recon-all (Interface: ReconAll)
	recon-all (Interface: ReconAll)
	recon-all (Interface: ReconAllRPT)
```

**Comment by giulia-berto** [comment]
I also have a question: does the preprocessing workflow make use of the freesurfer (reconall) output? Or is it only used by the reconstruction workflow?

**Comment by mattcieslak** [comment]
Hi @giulia-berto,
Starting at version 0.15 I removed most of the Freesurfer install because it took up a ton of space in the docker image and most users have been running freesurfer in a different pipeline (usually fmriprep). If you ran freesurfer outside of qsiprep, you can specify the location of your freesurfer results using `--freesurfer-input` option and the reconstruction workflows can use the freesurfer data. Preprocessing doesn't use freesurfer data for anything, but reconstruction can use the surfaces and segmentation if you use one of the mrtrix hsvs workflows

**Comment by giulia-berto** [comment]
Perfect, thank you @mattcieslak. Maybe it could be useful to specify that somewhere too.
