### ISSUE TITLE
Removing bad volumes prior to preprocessing

### ISSUE THREAD

**Issue by CaitlinLloyd** [PennLINC/qsiprep#492]
Hi,

I have been using QSIprep to preprocess data and it is working great generally, aside from when there is severe motion. In this case (and not unexpectedly), after using eddy_cuda to perform s2v correction, certain volumes continue to have artifacts. I am wondering if there is an alternative to manually checking the data or using the outlier maps (it looks like eddy_corrected.eddy_outlier_n_stdev_map is the only numeric matrix saved) to identify bad volumes to remove prior to reprocessing the data. In particular, is there a recommended method for removing bad volumes before running qsiprep for very large datasets? I saw a while ago there was a discussion about using a deep learning approach to this end.

Thank you very much!

Caitlin

**Comment by mattcieslak** [comment]
Hi! We've been thinking about this too, but don't have any official advice at the moment. One option would be to look at the `confounds.tsv` file produced for each scan. This has all the head motion parameters in it, including framewise displacement, which are commonly used to determine which volumes to remove from BOLD data due to motion. The framewise displacement values will be in a very different range from typical BOLD scans due to the long TR of dmri. 

I'd be interested to hear about what you've tried and how it's worked. Unlike resting BOLD, each volume in a dMRI scan samples a specific part of a scheme that may be the only volume sampling an important part of q-space. I'm sure some sampling schemes are more robust to losing volumes than others.
