### ISSUE TITLE
Distortion correction with blip

### ISSUE THREAD

**Issue by syunchoi** [PennLINC/qsiprep#493]
Hi,
I have a question regarding the Blip and multishell image. As you can see in my screenshot below, in my BIDS folder, I have Blip-LR, Blip-RL, and MB3multishell-LR. Does qsiprep automatically do distortion correction with blip data if I have blip files in the BIDS folder? Or do I have to set another option for distortion correction? 
Thank you!
<img width="319" alt="스크린샷 2022-11-22 오후 3 56 14" src="https://user-images.githubusercontent.com/118798176/203245733-d4d06470-b81a-4153-8ade-1b57ffa18155.png">

**Comment by mattcieslak** [comment]
By default all the DWI files will be combined and used to distortion correct one another. In this case do you want the two blip scans to be combined and the mb3 scan to be processed separately?

And do these blip images actually contain b>0 images or are they just b=0's?

**Comment by syunchoi** [comment]
Thanks for the reply!
If I want the two blip scans to be combined and the mb3 scan to be processed separately, then would it be possible to do?
And the blip images contain both b=0 and b>0 images. Below is the screenshot of the b values.

<img width="697" alt="스크린샷 2022-11-23 오후 4 40 47" src="https://user-images.githubusercontent.com/118798176/203493873-f9289cf7-f2c6-4413-b2e8-e48d52786453.png">

**Comment by mattcieslak** [comment]
In your case I would add sub-103_acq-blip* to the fmap/ directory along with the .bval and .bvec files. Then in your root .bidsignore file add `**fmap/*bval` and `**fmap/*bvec`. There aren't enough directions in either of the acq-blip images to do much, so you can take their b=0 images and use them for distortion correction. 

Note: once you move the acq-blip files to fmap/ you'll have to change their bids suffix to _epi instead of _dwi.
