### ISSUE TITLE
101-Direction DSI Sequence Preprocessing

### ISSUE THREAD

**Issue by mclaughlinj1** [PennLINC/qsiprep#550]
Hi there,

Our lab is currently in the process of building a pipeline to process our DSI data. We have been exploring the possibility of using QSIprep to accomplish this and have a few of questions. Our DSI sequence includes 101 gradient directions with 4 b0 using an A -> P phase encoding direction along with 4 additional b0 collected P -> A. 
 
1. What preprocessing steps would you recommend for our DSI sequence?

2. Should we be concerned about eddy current distortions in our data?

3. We have attempted to use the fsl topup/eddy workflow, which in the visual reports mention that the “q-space coordinates were forcefully assigned to shells.” Should we even do this with DSI data? Do you know of any other good options for DSI eddy current correction?

**Comment by mrribbits** [comment]
I've been playing with this myself (first time user).  This is what I've gathered so far, but anyone else please correct me if I'm wrong: 

- You'll have to use 3DShore instead of Eddy for motion correction (  --hmc_model 3dSHORE). 
- You should interleave B0s in your DSI scan for the motion correction (e.g. between every 10 b>0 volumes). 
- The scan should use bipolar diffusion scheme to reduce eddy currents (you set that at the scanner console).  
- I don't think you really need to collect the separate 4 b0s in A->P direction if you have those embedded in your DSI scan (just collect the separate 4 B0s in P->A direction). 
- From the DSI-Studio forums: At 3T with the 101 scheme, you can reduce the maximum b value to 3K. And if using the 258 scheme, you should use bmax=4K.   (Not exactly sure why the difference)
- For reference, in case this helps: my 101dir scan is about 6 min with MB=3, 2.4mm, TE=120ms, while my 258dir scan is about 11 min with MB=4, TE=132ms.  This is at a 3T Skyra.

**Comment by cookpa** [comment]
Wait, "--hmm-none" does hmc?

**Comment by mattcieslak** [comment]
Haha yes, trying the GitHub phone app

**Comment by mattcieslak** [comment]
It just uses the b=0s, so no model
