### ISSUE TITLE
Rename ACPC-aligned T1w/T2w space to something that is modality-independent

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsiprep#853]
## Summary

@mattcieslak and I have been discussing output naming and he noted that have "space-T1w" and "space-T2w" as the primary anatomical output space depending on the modality of the anatomical data is confusing and makes ingression difficult. We should use a name that is modality independent. Here are a few options we discussed:

- space-ACPC/acpc: This label is used for an iEEG coordinate system that is similar to what QSIPrep has. See https://bids-specification.readthedocs.io/en/stable/appendices/coordinate-systems.html#ieeg-specific-coordinate-systems
- space-anat: Because the space is derived from one or more anatomical images.
- space-individual: This is what BIDS recommends for a subject-specific anatomical space. See https://bids-specification.readthedocs.io/en/stable/appendices/coordinate-systems.html#nonstandard-coordinate-system-identifiers
- space-individualACPC: To clarify that the individual anatomical space is ACPC-aligned.
- space-anatACPC: To clarify that the individual anatomical space is ACPC-aligned.

Let's translate this to a vote. Please respond with the following:

👍  for space-ACPC
👎  for space-acpc
😄 for space-anat
🎉 for space-individual
😕 for space-individualACPC
❤️ for space-anatACPC
🚀 if you feel strongly that we need something else entirely

Vote for as many as you think are fine and we'll take the one with the highest count at the end. We can close the vote on Monday morning so that we have a few days to implement the change in time for the HBCD version release.

**Comment by mattcieslak** [comment]
My favorite by far is `space-ACPC`. It would create some very clear file names for the transforms, such as `from-T1w_to-ACPC`.

Historically, we've been using `T1w` as the name for the preprocessed, ACPC aligned subject space because that's what fmriprep used to use. There are some problems with this, such as 

 - Not all qsiprep users are fmriprep users, so `space-T1w` is very confusing
 - `space-T1w` in qsiprep has always meant "subject anatomy, but rigidly transformed to ACPC alignment"
 - Since `--anat-modality T2w` has been supported, The preprocessed dwis are still being written out to `space-T1w`
 - When querying a BIDSLayout for the preprocessed T1w/T2w in the derivatives you have to specify `space=Query.NONE`, which is super confusing/unintuitive

My second favorite would be `space-anatACPC` or `space-individualACPC` because it more explicitly reflects that it is a true anatomical space. It makes me think of the `acpc_dc` naming in the HCP-YA data - you know it is distortion-corrected and ACPC oriented. If we go this route I think it would also make sense to use `space-distortedACPC` if the ACPC alignment was based in a non-SDC'ed b=0 image.

**Comment by tsalo** [comment]
>Historically, we've been using T1w as the name for the preprocessed, ACPC aligned subject space because that's what fmriprep used to use.

I also think using T1w to mean the native T1w (without ACPC alignment) will make it easier to ingress anatomical derivatives from sMRIPrep/fMRIPrep. Currently, fMRIPrep's T1w != QSIPrep's T1w, but this would change that.

**Comment by smeisler** [comment]
I also like `space-ACPC`. I don't know if the `res` flag is only reserved for templates, but perhaps adding `res-native` would make it more clear to people that this is the subject T1w in ACPC alignment.

**Comment by cookpa** [comment]
I believe "res-" is allowed for all images but if it is present, the sidecar must include a Resolution dict like the templates do.

**Comment by araikes** [comment]
I don't know if the `res` flag is needed here since you're intentionally specifying an output resolution which is not inherently `native`

**Comment by tsalo** [comment]
I think we can close voting now. The space-ACPC option is the overwhelming winner.
